### ISSUE TITLE
Request feature to grab X-Y coordinates

### ISSUE THREAD

**Issue by plnnr** [jh-206/craigr#3]
This isn't an issue but more of a feature request. I notice that the X-Y coordinates are displayed somewhere in the DOM of a listing. Is it possible to add a parameter in the `get_query-internal.R` function to add the X-Y coordinates to the query? This would be immensely helpful. I had requested the address before, and you helped out with this, but as I try to geocode the query, I get pretty inconsistent results. Didn't realize what I actually wanted/needed (the X-Y coordinates) was in the DOM the entire time!

**Comment by jh-206** [comment]
From what I have seen, craigslist posts with a physical address (e.g. 123 main st) on the post have a google maps link that goes to that address. If, on the other hand, they just have the google link, it's a lat/lon pair. So it seems like you're either going to get a physical address or a lat/lon, but not both.

Does that coincide with what you have seen?

**Comment by plnnr** [comment]
When I inspect the elements on the page, the address field is sometimes lacking, but the user may have selected a location on a map. [Here](https://web.archive.org/web/20180920031937/https://portland.craigslist.org/mlt/apa/d/rent-specialfor-2br-15ba/6700313061.html) is an example, where the address is "144th. at Burnside." However, there is no intersection of 144th at Burnside (142nd or 146th, but not 144th). So if you click on the google maps link, it can't really locate it. 

The map on the ad webpage actually contains the X-Y coordinates even if the address is correctly entered. They are attributes of the `<div>` with an ID of `map`. For example:

    <div id="map" class="viewposting" data-latitude="45.522661" data-longitude="-122.514156" data-accuracy="5">

**Comment by jh-206** [comment]
Try using the code on the `jh-dev` branch. I need to test it out more before I merge with the `active` branch, and I'd appreciate your help testing. 

Also, it's confusing that the `master` branch is behind. I had it that way so that the original creator of the craigr repository would eventually see the address pull request and hopefully merge. But I plan on changing that so the master branch of this fork of the repository is the active one

**Comment by plnnr** [comment]
Thanks for adding the feature! Sorry I’m a noob but do you know how I would install/access the dev version into R?

**Comment by jh-206** [comment]
`devtools::install_github("jh-206/craigr", ref = "jh-dev")`

**Comment by plnnr** [comment]
Thanks for the tip. After running a query and inspecting the output, I would make one more suggestion—to add another column `location-accuracy` that is based on the `data-accuracy` attribute in `#map` div. It seems that sometimes the geolocation is just some arbitrary geometric centroid, or a vague location. I'm not sure how the map wrapper works, but it must adjust the initial zoom level and map pin/location icon (i.e., a pin drop vs a bubble/circle around the estimated location) based on the `data-accuracy` attribute. If this field was added to the output, then users could determine whether the accuracy of the geolocation is suitable for their needs.

**Comment by jh-206** [comment]
Check latest commit

**Comment by jh-206** [comment]
Features added and merged into `active` branch. Please test and open new issue if bugs arise

**Comment by plnnr** [comment]
Thanks! This worked perfectly. But `XYAccuracy` was spelled wrong (“accruacy” instead of “accuracy”).

**Comment by jh-206** [comment]
whoops
corrected

**Comment by plnnr** [comment]
I did `devtools::install_github("jh-206/craigr", branch = "active")` and when I run a command to grab XY coordinates, it says `Error in get_query(query_url, ...) : unused argument (get_xy = TRUE)`. Did I install your merge correctly?

**Comment by jh-206** [comment]
`devtools::install_github("jh-206/craigr", ref = "active")`

Gotta use `ref` not `branch`
